In [ ]:
import pandas as pd
import openpyxl as pxl

df = pd.read_csv("casos_ejemplo.csv")

df.info

<bound method DataFrame.info of          ID_Caso Fecha_Ingreso Sucursal_Propietaria     Ejecutivo  \
0    CASO-100001    2026-08-03            Quilicura  Ejecutivo_05
1    CASO-100002    2026-07-29      Santiago Centro  Ejecutivo_10
2    CASO-100003    2026-07-25      Santiago Centro  Ejecutivo_14
3    CASO-100004    2026-07-26                Maipú  Ejecutivo_13
4    CASO-100005    2026-08-03          Puente Alto  Ejecutivo_11
..           ...           ...                  ...           ...
795  CASO-100796    2026-07-16      Santiago Centro  Ejecutivo_12
796  CASO-100797    2026-07-25                Ñuñoa  Ejecutivo_12
797  CASO-100798    2026-08-12           Las Condes  Ejecutivo_07
798  CASO-100799    2026-07-21            Quilicura  Ejecutivo_10
799  CASO-100800    2026-07-28           La Florida  Ejecutivo_13

                Tipificacion     Subtipificacion  Dias_Cartera      Estado  \
0         Servicio adicional  Despacho adicional            17   Pendiente
1                 Devolución         En revisión            22   Pendiente
2    Problema de facturación              Boleta            26   Pendiente
3        Reembolso pendiente     Pendiente banco            25   Pendiente
4         Servicio adicional              Armado            17   Pendiente
..                       ...                 ...           ...         ...
795       Servicio adicional              Armado            35    Escalado
796      Reembolso pendiente     Pendiente banco            26    Escalado
797   Consulta transaccional  Estado transacción             8  En gestión
798       Servicio adicional              Armado            30   Pendiente
799      Anulación de compra        Error compra            23   Pendiente

    Prioridad Canal_Ingreso  Monto_Compra Cumple_SLA_7_dias M20  \
0       Media   Call Center        109672                No  No
1        Alta        Tienda         31639                No  Sí
2       Media           Web         22205                No  Sí
3        Baja           Web         61677                No  Sí
4       Media        Tienda         37930                No  No
..        ...           ...           ...               ...  ..
795      Baja           App         45297                No  Sí
796     Media   Call Center         91394                No  Sí
797     Media   Call Center        132173                No  No
798      Alta        Tienda        130942                No  Sí
799      Alta           App        204679                No  Sí

    Contacto_Cliente Escalado      Resultado_Gestion
0                 Sí       No               Derivado
1                 Sí       Sí         En seguimiento
2                 Sí       Sí               Resuelto
3                 Sí       Sí  Pendiente información
4                 Sí       No         En seguimiento
..               ...      ...                    ...
795               Sí       Sí               Derivado
796               Sí       No               Derivado
797               Sí       No     Cliente contactado
798               Sí       Sí         En seguimiento
799               Sí       Sí     Cliente contactado

[800 rows x 16 columns]>

In [10]:
df.describe()

       Dias_Cartera   Monto_Compra
count    800.000000     800.000000
mean      18.488750  126645.487500
std       10.167305   70531.568999
min        1.000000    5028.000000
25%       10.000000   65640.500000
50%       18.000000  124352.000000
75%       27.250000  189208.750000
max       35.000000  249942.000000

In [9]:
df_ejecutivos = df["Ejecutivo"]
df_ejecutivos.describe()

count              800
unique              15
top       Ejecutivo_08
freq                71
Name: Ejecutivo, dtype: object

In [8]:
print(df["Dias_Cartera"].max())

35

In [11]:
df.dtypes

ID_Caso                   str
Fecha_Ingreso             str
Sucursal_Propietaria      str
Ejecutivo                 str
Tipificacion              str
Subtipificacion           str
Dias_Cartera            int64
Estado                    str
Prioridad                 str
Canal_Ingreso             str
Monto_Compra            int64
Cumple_SLA_7_dias         str
M20                       str
Contacto_Cliente          str
Escalado                  str
Resultado_Gestion         str
dtype: object

In [15]:
df.to_excel("casos.xlsx", sheet_name="hoja1", index=False)

In [17]:
df2 = pd.read_excel("casos.xlsx")
df2.head()

,ID_Caso,Fecha_Ingreso,Sucursal_Propietaria,Ejecutivo,Tipificacion,Subtipificacion,Dias_Cartera,Estado,Prioridad,Canal_Ingreso,Monto_Compra,Cumple_SLA_7_dias,M20,Contacto_Cliente,Escalado,Resultado_Gestion
0,CASO-100001,2026-08-03,Quilicura,Ejecutivo_05,Servicio adicional,Despacho adicional,17,Pendiente,Media,Call Center,109672,No,No,Sí,No,Derivado
1,CASO-100002,2026-07-29,Santiago Centro,Ejecutivo_10,Devolución,En revisión,22,Pendiente,Alta,Tienda,31639,No,Sí,Sí,Sí,En seguimiento
2,CASO-100003,2026-07-25,Santiago Centro,Ejecutivo_14,Problema de facturación,Boleta,26,Pendiente,Media,Web,22205,No,Sí,Sí,Sí,Resuelto
3,CASO-100004,2026-07-26,Maipú,Ejecutivo_13,Reembolso pendiente,Pendiente banco,25,Pendiente,Baja,Web,61677,No,Sí,Sí,Sí,Pendiente información
4,CASO-100005,2026-08-03,Puente Alto,Ejecutivo_11,Servicio adicional,Armado,17,Pendiente,Media,Tienda,37930,No,No,Sí,No,En seguimiento